### ISSUE TITLE
[refactor] watchlist 이름 편집 및 디테일 todo

### ISSUE THREAD

**Issue by bakhacode** [fine-ants/frontend#126]
## 구현해야 할것

- [x] mutation key 제거
- [x] 프로필 사진 밑에 원 제거
- [x] wide legend 바닥부분에 붙는 현상 수정 (붙어있어도 괜찮다는 의견)
- [x] watchlist 헤드 별표 삭제
- [x] watchlist 이름 편집 기능 추가
