### ISSUE TITLE
사소한 TODO 처리하기

### ISSUE THREAD

**Issue by altmit** [fine-ants/frontend#50]
## 구현해야 할것
- [x]  Header에 로고 클릭시 로그인 상태 비교해서 랜딩 or 대시보드
- [x] 사용하지 않는 이미지, 아이콘 지우기
  - [x] 이미지, 아이콘 정리
- [x] 검색 에러 토스트 제거
- [x] 조회 실패 토스트 제거
- [x] 토스트 위치 변경
- [x] refetchOnWindowFocus 옵션 제거

## 기타
- TODO에 쌓인 부채 처리하기
